// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Marain.ContentManagement.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CreateContent")]
    [NUnit.Framework.CategoryAttribute("setupContainer")]
    [NUnit.Framework.CategoryAttribute("setupTenantedCosmosContainer")]
    public partial class CreateContentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateContent.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateContent", "\tIn order to manage content\r\n\tAs a developer\r\n\tI want to be create and retrieve c" +
                    "ontent", ProgrammingLanguage.CSharp, new string[] {
                        "setupContainer",
                        "setupTenantedCosmosContainer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create and get content")]
        public virtual void CreateAndGetContent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create and get content", null, ((string[])(null)));
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Id",
                        "Slug",
                        "Tags",
                        "CategoryPaths",
                        "Author.Name",
                        "Author.Id",
                        "Title",
                        "Description",
                        "Culture",
                        "Fragment"});
            table4.AddRow(new string[] {
                        "Expected",
                        "{newguid}",
                        "/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text"});
#line 9
 testRunner.Given("I have created content with a content fragment", ((string)(null)), table4, "Given ");
#line 12
 testRunner.When("I get the content with Id \'{Expected.Id}\' and Slug \'{Expected.Slug}\' and call it " +
                    "\'Actual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("the content called \'Expected\' should match the content called \'Actual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create multiple content records for the same slug")]
        public virtual void CreateMultipleContentRecordsForTheSameSlug()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create multiple content records for the same slug", null, ((string[])(null)));
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Id",
                        "Slug",
                        "Tags",
                        "CategoryPaths",
                        "Author.Name",
                        "Author.Id",
                        "Title",
                        "Description",
                        "Culture",
                        "Fragment"});
            table5.AddRow(new string[] {
                        "ExpectedFirst",
                        "{newguid}",
                        "/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 1"});
            table5.AddRow(new string[] {
                        "ExpectedSecond",
                        "{newguid}",
                        "/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 2"});
            table5.AddRow(new string[] {
                        "ExpectedThird",
                        "{newguid}",
                        "/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 3"});
            table5.AddRow(new string[] {
                        "ExpectedFourth",
                        "{newguid}",
                        "/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 4"});
#line 16
 testRunner.Given("I have created content with a content fragment", ((string)(null)), table5, "Given ");
#line 22
 testRunner.When("I get the content with Id \'{ExpectedFirst.Id}\' and Slug \'{ExpectedFirst.Slug}\' an" +
                    "d call it \'ActualFirst\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.And("I get the content with Id \'{ExpectedSecond.Id}\' and Slug \'{ExpectedSecond.Slug}\' " +
                    "and call it \'ActualSecond\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I get the content with Id \'{ExpectedThird.Id}\' and Slug \'{ExpectedThird.Slug}\' an" +
                    "d call it \'ActualThird\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I get the content with Id \'{ExpectedFourth.Id}\' and Slug \'{ExpectedFourth.Slug}\' " +
                    "and call it \'ActualFourth\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("the content called \'ExpectedFirst\' should match the content called \'ActualFirst\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.And("the content called \'ExpectedSecond\' should match the content called \'ActualSecond" +
                    "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("the content called \'ExpectedThird\' should match the content called \'ActualThird\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("the content called \'ExpectedFourth\' should match the content called \'ActualFourth" +
                    "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get content summaries for a given slug")]
        public virtual void GetContentSummariesForAGivenSlug()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get content summaries for a given slug", null, ((string[])(null)));
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Id",
                        "Slug",
                        "Tags",
                        "CategoryPaths",
                        "Author.Name",
                        "Author.Id",
                        "Title",
                        "Description",
                        "Culture",
                        "Fragment"});
            table6.AddRow(new string[] {
                        "ExpectedFirst",
                        "{newguid}",
                        "some/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 1"});
            table6.AddRow(new string[] {
                        "ExpectedSecond",
                        "{newguid}",
                        "some/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 2"});
            table6.AddRow(new string[] {
                        "ExpectedThird",
                        "{newguid}",
                        "some/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 3"});
            table6.AddRow(new string[] {
                        "ExpectedFourth",
                        "{newguid}",
                        "some/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 4"});
#line 32
 testRunner.Given("I have created content with a content fragment", ((string)(null)), table6, "Given ");
#line 38
 testRunner.When("I get the content summaries for Slug \'some/slug/\' with limit \'20\' and continuatio" +
                    "nToken \'{null}\' and call it \'Actual\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContentName"});
            table7.AddRow(new string[] {
                        "ExpectedFourth"});
            table7.AddRow(new string[] {
                        "ExpectedThird"});
            table7.AddRow(new string[] {
                        "ExpectedSecond"});
            table7.AddRow(new string[] {
                        "ExpectedFirst"});
#line 39
 testRunner.Then("the content summaries called \'Actual\' should match", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get batched content summaries for a given slug")]
        public virtual void GetBatchedContentSummariesForAGivenSlug()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get batched content summaries for a given slug", null, ((string[])(null)));
#line 46
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Id",
                        "Slug",
                        "Tags",
                        "CategoryPaths",
                        "Author.Name",
                        "Author.Id",
                        "Title",
                        "Description",
                        "Culture",
                        "Fragment"});
            table8.AddRow(new string[] {
                        "ExpectedFirst",
                        "{newguid}",
                        "batch/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title 1",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 1"});
            table8.AddRow(new string[] {
                        "ExpectedSecond",
                        "{newguid}",
                        "batch/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title 2",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 2"});
            table8.AddRow(new string[] {
                        "ExpectedThird",
                        "{newguid}",
                        "batch/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title 3",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 3"});
            table8.AddRow(new string[] {
                        "ExpectedFourth",
                        "{newguid}",
                        "batch/slug/",
                        "First tag; Second tag",
                        "/standard/content;/books/hobbit;/books/lotr",
                        "Bilbo Baggins",
                        "{newguid}",
                        "This is the title 4",
                        "A description of the content",
                        "fr-FR",
                        "This is the fragment of text 4"});
#line 47
 testRunner.Given("I have created content with a content fragment", ((string)(null)), table8, "Given ");
#line 53
 testRunner.When("I get the content summaries for Slug \'batch/slug/\' with limit \'2\' and continuatio" +
                    "nToken \'{null}\' and call it \'ActualBatch1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.And("I get the content summaries for Slug \'batch/slug/\' with limit \'2\' and continuatio" +
                    "nToken \'{ActualBatch1.ContinuationToken}\' and call it \'ActualBatch2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContentName"});
            table9.AddRow(new string[] {
                        "ExpectedFourth"});
            table9.AddRow(new string[] {
                        "ExpectedThird"});
#line 55
 testRunner.Then("the content summaries called \'ActualBatch1\' should match", ((string)(null)), table9, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "ContentName"});
            table10.AddRow(new string[] {
                        "ExpectedSecond"});
            table10.AddRow(new string[] {
                        "ExpectedFirst"});
#line 59
 testRunner.And("the content summaries called \'ActualBatch2\' should match", ((string)(null)), table10, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
